### PR TITLE
Making TAP publisher compatible with Jenkins 2 pipeline scripts + couple of fixes

### PR DESCRIPTION
**Pull request by anenviousguest**
# Main part
... so that it's possible to use it in Jenkinsfile groovy scripts as a generic step, for example: 
```
step([$class: "TapPublisher", testResults: "**/target/tap-unit.log"])
```
This ability was actually almost there. The missing part was for `TapPublisher` to implement `SimpleBuildStep` and make it and its surroundings rely on `hudson.model.Run` instead of `hudson.model.AbstractBuild`.

# Minor parts
1. Basic unit test for the publisher itself was added.
2. Publisher constructor was not specifying default value for `outputToConsole` parameter.
3. Some quirks in the URLs in "Failed tests" table. In a unit test I discovered that it was somehow containing `(empty)` chunk so that resulting URL was inaccessible.

### CODE REVIEW

**Comment by anenviousguest** [comment]
trigger jenkins re-build as the previous one failed

**Comment by anenviousguest** [comment]
@kinow hi Bruno. Have you had any chance to review this?
Thanks.

**Comment by kinow** [comment]
Hi @anenviousguest, sorry not yet. Feel free to ping me again in a few weeks if I haven't had the chance to review it. In the past I used to have sponsoring to work on some of the Jenkins plug-ins, but now it's all done in my spare time, as volunteer work, so hope you can understand that it may take a while to review it :smiley:

**Comment by anenviousguest** [comment]
@kinow Hi Bruno,

Hope you're doing well.
I have just augmented PR a bit to allow merging results when more than one publisher was added to the build.
Looking forward to have you reviewed that :-)

Thanks.

**Comment by anenviousguest** [comment]
Related ticket: https://issues.jenkins-ci.org/browse/JENKINS-34000

**Comment by pjanuario** [comment]
Indeed, I am also migrating for the new pipeline to build nodejs app and this would really nice to have too.

**Comment by kinow** [comment]
Looking good @anenviousguest 

Tested locally with the following script successfully

```
stage 'Build'

node {
  sh 'cat > tap.t <<EOF\n1..2\nok 1\nok 2\nEOF'
  step([$class: "TapPublisher", testResults: "**/*.t"])
}
```

Will merge manually the pull request now :+1:

**Pull request merged**
