### PR TITLE
Use standard utility to escape html characters.

### PR DESCRIPTION
**Pull request by ranford**
I suspect (but haven't proven) that this may be the cause of [this bug](https://issues.jenkins-ci.org/browse/JENKINS-32729).

### CODE REVIEW

**Comment by kinow** [comment]
I can spend some time testing it. Thanks for pointing one solution @ranford. I **think** I saw some new package in Jenkins with classes with utility methods. Maybe somewhere in the core there is a function doing something similar. Let's see :-) thanks again

**Comment by ranford** [comment]
While I think this PR or something like it is probably a good idea, looking closer I don't think it is the fix for that bug. 

Actually, I just did a fresh install of Jenkins and the TAP-Plugin, and I couldn't reproduce the issue. Perhaps it was a Jenkins bug that has since been fixed?

**Comment by kinow** [comment]
Could be something in one of the newer releases. 

Before we were trying to do some clever string replacement, but I remember adding (or it was enforced by Jenkins core) some XML tag, to stapler files, that prevented XSS by escaping characters.

I'm working on image-gallery and nunit, and have released tap some time ago. So will finish with these other plug-ins before reviewing tap again. Feel free to update this pull request in case you find any other interesting thing.

**Comment by kinow** [comment]
Confirmed in the linked issue in JIRA, as well as in that issue's other related issue, that the issue cannot be reproduced. In 1.580.1 nor in 2.7.2. But thanks for the contribution anyway @ranford !

**Pull request closed without merging**
